# Generated by Django 3.1.4 on 2020-12-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='title')),
                ('Network', models.CharField(max_length=30, verbose_name='network')),
                ('Release_date', models.DateField(verbose_name='release_date')),
                ('Description', models.TextField(max_length=200, verbose_name='description')),
            ],
        ),
    ]
