# Generated by Django 3.0.5 on 2020-12-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
